### PR TITLE
VirtualCollection recomputation checkbox

### PR DESCRIPTION
**Pull request by manuelbernhardt**

### CODE REVIEW

**Comment by kiivihal** [comment]
This feature request was more related to actually recreating the actual virtual collection based on the query at certain intervals. Is this something you can easily add to this pull request as well.

**Comment by manuelbernhardt** [comment]
To make sure: when that box is checked, the collection should be automatically re-created at a certain interval?

**Comment by kiivihal** [comment]
Yes as if you hit save manually after the preview. So default should be false, and you can enable it via the interface.

## 

Sjoerd Siebinga
Delving B.V., Rotterdam
http://www.delving.eu (http://www.delving.eu/)
skype: sjoerdsiebinga
mobile: +31681926731

**Comment by manuelbernhardt** [comment]
The checkbox is doing what it is supposed to do now.

**Pull request merged**
