### PR TITLE
Replacing WebSockets with Comet

### PR DESCRIPTION
**Pull request by manuelbernhardt**
- infinite iframe technique with long-lasting connection
- alerting users when the connection dies
- subscribers are removed if they don't ping the server in a given time-frame
- some browsers will display a forever loading wheel on the page, but this is the only technology that will work across all browsers & connections

### CODE REVIEW

**Comment by geralddejong** [comment]
I fetched the branch and tried it out.  It makes my browser think that it is constantly loading, which is weird because the mouse has the pause icon (Linux) everywhere.

**Comment by manuelbernhardt** [comment]
Unfortunately that's how Comet works. Feel free to Google it.

**Comment by geralddejong** [comment]
Ok then comet sucks too, unless there's something  surmountable keeping us from enjoying the pleasures of websockets.

**Comment by manuelbernhardt** [comment]
The mouse works fine on OS X, and from what I know of Comet, on Windows as
well. I don't think a majority of the people using the DataSet page uses
Linux.

The "forever loading" sign on the browser may be an inconvenience, but not
so much as the whole connection dropping, which is what this pull requests
aims to address.

In the end, the question is how much effort is it worth making this part of
the site behaving perfectly, vs making it robust.

**Comment by geralddejong** [comment]
I guess if Linux is the only case where it looks funny, we should not be worried.

**Pull request merged**
