### PR TITLE
Indexing control

### PR DESCRIPTION
**Pull request by manuelbernhardt**
First shot at an indexing control interface

### CODE REVIEW

**Comment by kiivihal** [comment]
I have update  the schema of core2 so that all metadata gets indexed. 

There are two issues I noticed. One is minor that the alignment of the re-index and disable button is not right. The other one is a bit more serious. When you index the state is not update and remains at _cancel-indexing_ and only on a page-refresh is it updated. So if you could fix that issue, I will merge it into master.

**Comment by geralddejong** [comment]
I started an indexing, which failed (because the expected mapping wasn't found).  There was no report of this in the interface,  the "cancel indexing" button remained, and the progress bar remained white.  I only knew what happened from reading the log.

I also had no solr started up, and when I pressed "cancel" on this indexing I had started, I was shown a problem in the code (resulting from the ConnectException(connection refused)), which I suppose will not happen in production.

When I switched my URL to http://localhost:9000/bob/dataset/ it said "DataSet 'null' was not found".

When I started indexing on another dataset (this one did have the proper mapping) the progress bar appeared and proceeded to move.  Meanwhile no solr was started and a million errors appear in the log.  It should give up at some point.  After starting up solr, it started working normally.

**Comment by geralddejong** [comment]
Starting up I get this:

```
Execution exception (In /app/util/ThemeHandlerComponent.scala around line 124)
NoSuchElementException occured : None.get

play.exceptions.JavaExecutionException: None.get
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
    at Invocation.HTTP Request(Play!)
Caused by: java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:262)
    at scala.None$.get(Option.scala:260)
    at util.ThemeHandler.getByRequest(ThemeHandlerComponent.scala:124)
```

**Comment by geralddejong** [comment]
Turns out the above problem was solved by deleting the PortalThemes collection in mongodb.

Indexing seems to work for two collections.  Since there is no search implemented I attempted to find the indexed information using solr (http://localhost:8983/solr/coreN/admin/) searching for star-colon-star, but I only see empty responses.

```
INFO: [core0] webapp=/solr path=/select/ params={indent=on&start=0&q=*:*&version=2.2&rows=10} hits=0 status=0 QTime=2
```

For other collections, upon starting indexing I see "Error occured while indexing DataSet" but there is no other information, and nothing whatsoever even appears in the log.

**Comment by manuelbernhardt** [comment]
I am not familiar enough with solr yet to tell exactly what is going on with indexing, but since I see a lot of things happening in the solr log I assume that some form of indexing is taking place. So I'd like to think that we'll have that sorted out when integrating with the search.

About error reporting, indeed nothing is reported to the user, essentially because of the current implementation of the indexing task creation which is very rudimentary. Basically, there is no separate task created when indexing something, so all messages that would need to be presented to the user upon indexing would need to be stuffed into the DataSet and that is not something I am terribly fond of. We instead should have an IndexingTask that holds this kind of information.

Additionally, it should probably not be possible to start indexing a DataSet if there is no fitting mapping for the main mapping defined by the theme (which is "icn" by default). Currently you can run things anyway and that will lead to the error you see, but without any information (other than the fact that there is an error).

Since this is a "first shot" at the indexing interface, I'd propose to use this pull request even though it is incomplete, and have me do another iteration on it in 2 days (by then I should be done with the first version of the image server). That will at least make it possible for Sjoerd to start indexing stuff while developing the search.

**Comment by manuelbernhardt** [comment]
Please ignore the open/close, I hit the wrong button.

**Pull request merged**
