### PR TITLE
Object server integration

### PR DESCRIPTION
**Pull request by manuelbernhardt**
This branch integrates the new object server with CultureHub in a "local" operation mode (i.e., tied to the deployed culture-hub).

One effect of this is that the preferred way of retrieving ingested thumbnails is to call them via `orgId/collectionId/id` instead of just `id`, where `id` is the fileName of the ingested thumbnail. However, the change is backwards-compatible, so only a warning is issued for old requests. But deployed thumbnail consumers should probably get a mapping update (and the thumbnails be re-ingested).

Correctly running this branch requires to run `setup-play.sh` or at least the part that fetches the DoS.

### CODE REVIEW

**Comment by geralddejong** [comment]
play deps gives:

```
~ WARNING: These dependencies are missing, your application may not work properly (use --verbose for details),
~
~   dos->dos ->
```

**Comment by manuelbernhardt** [comment]
Have you re-run `setup-play.sh`? Or this part of it:

```
cd module-extra
git clone git://github.com/delving/dos.git dos
cd dos
play deps --sync
ant -Dplay.path=../../../play
cd ../../
```

**Comment by geralddejong** [comment]
The git syntax seems to be:

git clone git@github.com:delving/dos.git

I have tried those commands separately but the build file failed because it didn't find scala-0.9.1, so now I'm running setup-play.sh itself.

**Comment by manuelbernhardt** [comment]
I just pushed out a new version of the setup file. Sorry for the mess, my DoS version had already some of the directories created

**Comment by geralddejong** [comment]
Seems to work nicely for uploading images and serving them up, which is probably the main thing for this pull.

**Pull request merged**
